### ISSUE TITLE
Missing features

### ISSUE THREAD

**Issue by Fargus5** [IcyFlameX/GTACops#2]
Hi

I have MC Version 1.12 of spigot
And the plugins works as aspected.
I have problems because it is in conflict with other plugins that I have already installed.

1)	RPGPlayerLeveling : https://www.spigotmc.org/resources/rpg-player-leveling.11096/
2)	And NameTagEdit: https://www.spigotmc.org/resources/nametagedit.3836/

About the first one the problem is with the scoreboard… GTACops just get off the others scoreboards… so maybe I would like to use GTACops, but I need to completely disable the scoreboard system to let RPGPL works correctly.

About the second one, edited name are not anymore visible in the tablist because this plugin doesn’t support GTACops and stars doesn’t appears… I already see that in the config there is this option and we can disable it, I didn’t do it, but I have to try if disabling this NTE will work or not.

Could you improve this please?

Maybe also the possibility to change the maximal range of /callcop ?

Could u also please to add the possibility to use this command /callcop without a player name? it will check automatically if someone is within 10 blocks and it hitted u? maybe the possibility to specify how mutch time he has to hit you to be considered by the cops?

Thanks in advance

Claudio

**Comment by IcyFlameX** [comment]
Hello Claudio,

First of all thank you very much for reporting this issue.

Explanation: 
2nd Issue:
Can you explain a bit more, what do u mean by edited names ?
Also as of 1.4.9 update, you can no longer see other player's stars temporarily. It will be fixed soon. I did it because many people complained it conflicted with scoreboards like featherboard. It will be soon re-implemented.

1st issue:
See, my plugin follows the rules of Bukkit, which means every player has its own personal scoreboard, thereby reducing lag and stopping conflict with many plugins. It just might be possible RPG plugin has only one universal scoreboard for which its conflicting with mine, however i cant blame the author since i am not sure, therefore i will try my best to adjust my own plugin.
3rd Issue:
Thanks for the suggestion, i will see what i can do to it.

Stay tuned for the updates and fixes. Sorry for all the problems which you might have faced. 

Regards
~Icy <3

**Comment by Fargus5** [comment]
2nd issue:
Edited names... name that are changed using the NameTagEdit. Adding GTACops each edit disappears.

Anyway thank you for the support, I will take this issue open to let u work on it and update it

I'm obliged to unistall GTACops untill all of this will not be implemented

Thanks a lot

**Comment by Fargus5** [comment]
?

**Comment by IcyFlameX** [comment]
Hello Fargus5,
First of all sorry for not responding to your issue. I am deeply sorry. I have been lately busy with my exams. 
As for the issue I would like to notify you that I have added /callcop.
I added option to change the range.
I am looking if I can edit the command /callcop without asking player's name.
I had used the tag because I couldn't find a way to hook placeholder in Featherboard and other stuff. I am happy to say I have successfully created placeholders which you can hook in Featherboard thereby removing tag.
Sorry yet again.
Regards
~Icy <3

**Comment by Fargus5** [comment]
Dear

Ok thanks let me know

**Comment by IcyFlameX** [comment]
Matter Closed due to issue being fixed.
